# -*- coding: utf-8 -*-
"""gradio_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuL4ctcfiRhVJN6fbgOHY65dJFp_uwRV
"""

import gradio as gr
import requests
import json

# Your live AWS API endpoint
API_URL = "http://52.15.208.206/predict"

def predict_readmission(patient_text):
    """
    Takes the raw patient text, sends it to the AWS API, and returns the results.
    """
    if not patient_text or len(patient_text.strip()) == 0:
        return "⚠️ Please enter patient text.", "", "", ""

    payload = {
        "patient_id": "gradio_user_001",
        "clinical_text": patient_text
    }

    try:
        response = requests.post(API_URL, json=payload, timeout=30)

        if response.status_code == 200:
            data = response.json()

            risk_class = data.get("risk_class", "Unknown")
            prob_no = data["probabilities"].get("NO", 0)
            prob_30 = data["probabilities"].get(">30 days", 0)
            prob_less = data["probabilities"].get("<30 days", 0)
            alert = data.get("risk_alert", False)

            alert_status = "🚨 HIGH RISK (<30 days)" if alert else "✅ Low Risk (NO)"
            prob_text = f"""
            **Predicted Probabilities:**
            - NO: {prob_no:.2%}
            - >30 days: {prob_30:.2%}
            - <30 days: {prob_less:.2%}
            """

            if risk_class == "<30 days":
                risk_display = f"🔴 {risk_class}"
            elif risk_class == ">30 days":
                risk_display = f"🟡 {risk_class}"
            else:
                risk_display = f"🟢 {risk_class}"

            return risk_display, prob_text, alert_status, "✅ Prediction generated successfully!"
        else:
            return "❌ API Error", "", "", f"Error: {response.status_code} - {response.text}"

    except requests.exceptions.ConnectionError:
        return "❌ Connection Error", "", "", "Could not reach the AWS API. Is the server running?"
    except Exception as e:
        return "❌ Error", "", "", str(e)

# Build the Gradio Interface
with gr.Blocks(title="Readmission Risk Predictor, Decision Support", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🏥 Hospital Readmission Risk Predictor, NOT a replacement for clinical assessment!")
    gr.Markdown("Paste the patient's clinical context text below to get a 30-day readmission risk prediction.")

    with gr.Row():
        with gr.Column(scale=2):
            input_text = gr.Textbox(
                label="Patient Clinical Text",
                placeholder="Paste the patient context here...",
                lines=15,
                max_lines=30
            )
            submit_btn = gr.Button("🚀 Predict Risk", variant="primary")

        with gr.Column(scale=1):
            output_risk = gr.Textbox(label="Predicted Risk Class", interactive=False)
            output_probs = gr.Markdown(label="Predicted Probabilities")
            output_alert = gr.Textbox(label="Risk Alert", interactive=False)
            output_status = gr.Textbox(label="Status", interactive=False)

    submit_btn.click(
        fn=predict_readmission,
        inputs=input_text,
        outputs=[output_risk, output_probs, output_alert, output_status]
    )
    gr.Markdown("### 📋 Quick Test Examples")
    gr.Examples(
        examples=[
            ["Patient's context Race: Caucasian. Gender: Female. Age: [20-30). admission type: Elective. Number of days between admission and discharge: 1. Number of medications administered during the encounter: 11. Number of emergency visits in the year preceding: 3. Number of inpatient visits in the year preceding: 1. insulin dosage change: Up. Change in diabetic medication dosage: Ch. Classification:>30 days."],
            ["Patient's context Race: Caucasian. Gender: Male. Age: [10-20). admission type: Elective. Number of days between admission and discharge: 1. Number of medications administered during the encounter: 2. Number of emergency visits: 0. insulin dosage change: No. Classification:NO."]
        ],
        inputs=[input_text],
        label="Try these examples"
    )

    # Footer Disclaimer
    gr.Markdown("---")
    gr.Markdown("⚠️ **Disclaimer:** This tool estimates 30-day readmission risk based on historical clinical patterns "
    "observed across diverse patient populations. It is intended for **decision-support purposes only** and should "
    "be interpreted alongside the **individual patient's** current clinical condition and professional judgment.")
if __name__ == "__main__":
    demo.launch(share=True, server_name="0.0.0.0", server_port=7860)
