# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N08XD-j2yepI3R6_oWP90Y0pQm66KWnl
"""

import streamlit as st
import requests
import pandas as pd

# ----------------------------
# PAGE CONFIGURATION
# ----------------------------
st.set_page_config(
    page_title="Readmission Risk Predictor",
    page_icon="🏥",
    layout="centered"
)

# ----------------------------
# HEADER & DISCLAIMER
# ----------------------------
st.title("🏥 Hospital Readmission Risk Predictor")
st.caption("⚠️ **Decision-support tool only.** Please Add Your clinical judgment!")

# Your live AWS API endpoint
API_URL = "http://52.15.208.206/predict"

st.markdown("---")

# ----------------------------
# INPUT SECTION
# ----------------------------
patient_text = st.text_area(
    "Patient Clinical Context",
    height=150,
    placeholder="Paste the patient context here..."
)

# ----------------------------
# PREDICTION LOGIC
# ----------------------------
if st.button("🚀 Predict Risk", type="primary"):
    if not patient_text or len(patient_text.strip()) == 0:
        st.warning("⚠️ Please enter patient clinical text.")
    else:
        payload = {
            "patient_id": "streamlit_user_001",
            "clinical_text": patient_text
        }

        with st.spinner("⏳ Calling prediction API..."):
            try:
                response = requests.post(API_URL, json=payload, timeout=30)

                if response.status_code == 200:
                    data = response.json()

                    # Extract data
                    risk_class = data.get("risk_class", "Unknown")
                    probs = data.get("probabilities", {})
                    prob_no = probs.get("NO", 0)
                    prob_30 = probs.get(">30 days", 0)
                    prob_less = probs.get("<30 days", 0)
                    alert = data.get("risk_alert", False)

                    # ----------------------------
                    # METRICS ROW
                    # ----------------------------
                    col1, col2, col3 = st.columns(3)

                    # Risk Class with color coding
                    if risk_class == "<30 days":
                        risk_display = f"🔴 {risk_class}"
                    elif risk_class == ">30 days":
                        risk_display = f"🟡 {risk_class}"
                    else:
                        risk_display = f"🟢 {risk_class}"

                    col1.metric("Predicted Risk Class", risk_display)
                    col2.metric("Risk Alert", "🚨 HIGH" if alert else "✅ LOW")
                    col3.metric("Status", "Success" if alert else "Checked")

                    # ----------------------------
                    # PROBABILITY BAR CHART
                    # ----------------------------
                    st.subheader("📊 Predicted Probabilities")

                    prob_df = pd.DataFrame({
                        "Class": ["NO", ">30 days", "<30 days"],
                        "Probability": [prob_no, prob_30, prob_less]
                    })

                    # Display the bar chart
                    st.bar_chart(prob_df.set_index("Class"), height=300)

                    # ----------------------------
                    # DETAILED BREAKDOWN (SORTED DYNAMICALLY)
                    # ----------------------------
                    # Create a list of tuples (label, probability)
                    prob_list = [
                        ("NO", prob_no),
                        (">30 days", prob_30),
                        ("<30 days", prob_less)
                    ]

                    # Sort by probability (highest first)
                    prob_list_sorted = sorted(prob_list, key=lambda x: x[1], reverse=True)

                    # Create columns dynamically (one for each item)
                    cols = st.columns(len(prob_list_sorted))

                    # Display each metric in the sorted order
                    for i, (label, value) in enumerate(prob_list_sorted):
                        # Special formatting if it's the highest
                        delta_text = "🔺 Highest" if i == 0 else None
                        cols[i].metric(label, f"{value:.2%}", delta=delta_text)

                else:
                    st.error(f"❌ API Error: {response.status_code} - {response.text}")

            except requests.exceptions.ConnectionError:
                st.error("❌ Connection Error: Could not reach the AWS API. Is the server running?")
            except Exception as e:
                st.error(f"❌ Unexpected Error: {str(e)}")

# ----------------------------
# FOOTER DISCLAIMER (ALWAYS VISIBLE)
# ----------------------------
st.markdown("---")
st.markdown(
    "⚠️ **Disclaimer:** This tool estimates 30-day readmission risk based on historical clinical patterns "
    "observed across diverse patient populations. It is intended for **decision-support purposes only** and should "
    "be interpreted alongside the **individual patient's** current clinical condition and professional judgment."
)
)
